# Generated by Django 6.0.3 on 2026-03-21 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('course_code', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=200)),
                ('hall', models.CharField(max_length=100)),
                ('invigilator_name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('value', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'System Config',
                'verbose_name_plural': 'System Configs',
            },
        ),
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20)),
                ('student_name', models.CharField(max_length=200)),
                ('programme', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=10)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('invigilator_name', models.CharField(max_length=150)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='core.session')),
            ],
            options={
                'ordering': ['-verified_at'],
            },
        ),
    ]
